name: Build Life RPG Launcher

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cryptography requests

      - name: Build launcher EXE
        run: |
          pyinstaller --onefile --noconsole bootstrap.py

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/bootstrap.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
